DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
(
  Id BIGINT  PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
  Id BIGINT  PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(255),
  GENREID BIGINT,
  AUTHORSID BIGINT ,
  FOREIGN KEY (GENREID)  REFERENCES GENRE (Id),
  FOREIGN KEY (AUTHORSID)  REFERENCES AUTHORS (Id)
);

